---
# Source: ssd/templates/cm/ssd-mfe-platform.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-mfe-platform
  namespace: onework2
  labels:
    env: dev
    app.kubernetes.io/name: ssd
data:
  nginx.conf: |
    worker_processes  5;
    error_log   /var/log/ssd-v2/ssd-mfe-platform/error.log notice;
    pid        /tmp/nginx/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;
    }

    http {
      include  conf/mime.types;
      index    index.html;

      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      sendfile     on;
      tcp_nopush   on;
      
      client_body_temp_path /tmp/nginx/nginx-client-body;
      proxy_temp_path       /tmp/nginx/nginx-proxy;
      fastcgi_temp_path     /tmp/nginx/nginx-fastcgi;
      uwsgi_temp_path       /tmp/nginx/nginx-uwsgi;
      scgi_temp_path        /tmp/nginx/nginx-scgi;
      
      # sets value to `*` if not present:
      # default is *, but if any value exists already,
      # the new header will have and empty value, as a result will not be set
      map $upstream_http_access_control_allow_origin $add_wildcard_cors_if_not_exists {
        default '*';
        '~.' "";
      }

      server { # UI
        listen       3000;
        server_name  ssd-mfe-platform;
        access_log  /var/log/ssd-v2/ssd-mfe-platform/access.log main;
        root    /etc/nginx/html;
        gzip on;
        gzip_types application/json;
        large_client_header_buffers 4 32k;
    
        # Static in all directories
        location ~ ^(?<dir>\/((static|locales)\/((.+)\/)*)?)(?<file>([^\/]+)(\.[^\/.]+))$ {
            expires max;
        }
    
        location = /index.html {
            expires -1;
            add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        }
    
        # Common regexp for all static
        # ^(?<dir>\/((static|locales)\/((.+)\/)*)?)(?<file>([^\/]+)(\.[^\/.]+))$
    
        # Static in the root directory
        location ~ ^/([^\/]+)(\.[^\/.]+)$ {
          try_files $uri $uri/ =404;
        }
    
        # Static in other directories
        location ~ ^/(static|locales)/ {
          try_files $uri $uri/ =404;
        }
    
        location = / {
            index /index.html;
        }
    
        location / {
            try_files $uri $uri/ /index.html;
        }
    
        location = /health {
            access_log off;
            add_header Content-Type application/json;
            return 200 "{\"status\":\"pass\",\"releaseId\":\"1.17\",\"version\":\"1\",\"serviceId\":\"$hostname\",\"description\":\"health of mfe-poc\"}";
        }
      }
    }

  logrotate.conf: | 
    /var/log/ssd-v2/ssd-mfe-platform/access.log {
      rotate 5
      size 10M
      missingok
      copytruncate
      nocreate
      nodelaycompress
      nomail
      notifempty
      noolddir
      compress
      postrotate
            echo "Log /var/log/ssd-v2/ssd-mfe-platform/access.log was logrotated" && nginx -s reload
      endscript
    } 
    /var/log/ssd-v2/ssd-mfe-platform/error.log {
      rotate 5
      size 10M
      missingok
      copytruncate
      nocreate
      nodelaycompress
      nomail
      notifempty
      noolddir
      compress
      postrotate
            echo "Log /var/log/ssd-v2/ssd-mfe-platform/error.log was logrotated" && nginx -s reload
      endscript
    }
