---
# Source: ssd/templates/secrets/ssd-common-props.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-common-props
  namespace: onework2
  labels:
    helm.sh/chart: ssd-3.3.0
    env: dev
    app.kubernetes.io/name: ssd
    app.kubernetes.io/instance: ssd-infra
    app.kubernetes.io/version: "1.16.x"
    app.kubernetes.io/managed-by: Helm
stringData:
    secret-props.yml: |
      props-override:
        interservice-jwt-token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyN2V0Vk80X3Atamk0T19fRzJ5TVlMd1NLNzdsaDN5X0YzSUUxSktWVzJjIn0.eyJleHAiOjE3NjE3NTA1NzIsImlhdCI6MTc1OTE1ODU3MiwianRpIjoiMDgwZmUyNzMtMzc5MS00YWMwLTkyNGUtMThlNWZiYzkxNGY2IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay52b2RhLnJ1Ojg0NDMvcmVhbG1zL1dvcmtzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjI5M2I1NTkyLTk2ZjctNDcyNy1iYWRiLWM3ZTdjODk0ZTRmMCIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9uZXdvcmstbG9naW4iLCJzZXNzaW9uX3N0YXRlIjoiOTk4ZTc1ZTAtZjY4YS00OWI0LThmZDQtM2M3MWUyMzQ4NGJmIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTU0RfVVNFUiIsIlNTRF9TRVJWSUNFX1JPTEUiLCJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtd29ya3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiI5OThlNzVlMC1mNjhhLTQ5YjQtOGZkNC0zYzcxZTIzNDg0YmYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidHV6X3NzZF9pbnRlcnNlcnZpY2UiLCJnaXZlbl9uYW1lIjoiIiwiZmFtaWx5X25hbWUiOiIiLCJlbWFpbCI6InR1el9zc2RfaW50ZXJzZXJ2aWNlQHZvZGEuZ292LnJ1In0.Oot6kWIjxoXPgI7ePQsh07vMcCyJStw5Q9UGEbYTdb1cNAkGWYYV4bYI2l5-vz0655Gy5uyNqn9cEPnPQuG9G9lyZdjRH_43HtYc5xAvRPs--iNOYeEwVOvjzaPzvwGyuhKOo_1ArqNDG3zUcj4ybaKj5nyruh6E3upO8-q--SLObgSJTVVLRt-_Ifwqa0OZYXFSwGoBuH4KFiu_kvMH8gfWWuW_x_p_JvtryWzOW3oCUNd4nZb6OYx5QSCa4SSuaIcGGFnhyLYV2UE-SOk0S5KNKY2grVaXWcKZaKFVUwBcVg-tBpXEkjHiEpopnadxlYyiw4RJ5Fqu1u5njefNvw
        boot-admin:
          username: admin
          password: Admin
