---
# Source: ssd/templates/secrets/ssd-common.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-common
  namespace: onework2
  labels:
    helm.sh/chart: ssd-3.3.0
    env: dev
    app.kubernetes.io/name: ssd
    app.kubernetes.io/instance: ssd-infra
    app.kubernetes.io/version: "1.16.x"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  SSD_CLOUD_ADMIN_PASS: QWRtaW4=
  SSD_CLOUD_ADMIN_USER: YWRtaW4=
  SSD_DB_PASSWORD: c3Nk
  SSD_DB_USER: c3Nk
  SSD_JWT_SERVICE_TOKEN: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJZ09pQWlTbGRVSWl3aWEybGtJaUE2SUNKeU4yVjBWazgwWDNBdGFtazBUMTlmUnpKNVRWbE1kMU5MTnpkc2FETjVYMFl6U1VVeFNrdFdWekpqSW4wLmV5SmxlSEFpT2pFM05qRTNOVEExTnpJc0ltbGhkQ0k2TVRjMU9URTFPRFUzTWl3aWFuUnBJam9pTURnd1ptVXlOek10TXpjNU1TMDBZV013TFRreU5HVXRNVGhsTldaaVl6a3hOR1kySWl3aWFYTnpJam9pYUhSMGNITTZMeTlyWlhsamJHOWhheTUyYjJSaExuSjFPamcwTkRNdmNtVmhiRzF6TDFkdmNtdHpJaXdpWVhWa0lqb2lZV05qYjNWdWRDSXNJbk4xWWlJNklqSTVNMkkxTlRreUxUazJaamN0TkRjeU55MWlZV1JpTFdNM1pUZGpPRGswWlRSbU1DSXNJblI1Y0NJNklrSmxZWEpsY2lJc0ltRjZjQ0k2SW05dVpYZHZjbXN0Ykc5bmFXNGlMQ0p6WlhOemFXOXVYM04wWVhSbElqb2lPVGs0WlRjMVpUQXRaalk0WVMwME9XSTBMVGhtWkRRdE0yTTNNV1V5TXpRNE5HSm1JaXdpWVdOeUlqb2lNU0lzSW5KbFlXeHRYMkZqWTJWemN5STZleUp5YjJ4bGN5STZXeUpUVTBSZlZWTkZVaUlzSWxOVFJGOVRSVkpXU1VORlgxSlBURVVpTENKdlptWnNhVzVsWDJGalkyVnpjeUlzSW1SbFptRjFiSFF0Y205c1pYTXRkMjl5YTNNaUxDSjFiV0ZmWVhWMGFHOXlhWHBoZEdsdmJpSmRmU3dpY21WemIzVnlZMlZmWVdOalpYTnpJanA3SW1GalkyOTFiblFpT25zaWNtOXNaWE1pT2xzaWJXRnVZV2RsTFdGalkyOTFiblFpTENKdFlXNWhaMlV0WVdOamIzVnVkQzFzYVc1cmN5SXNJblpwWlhjdGNISnZabWxzWlNKZGZYMHNJbk5qYjNCbElqb2liM0JsYm1sa0lHVnRZV2xzSUhCeWIyWnBiR1VpTENKemFXUWlPaUk1T1RobE56VmxNQzFtTmpoaExUUTVZalF0T0daa05DMHpZemN4WlRJek5EZzBZbVlpTENKbGJXRnBiRjkyWlhKcFptbGxaQ0k2ZEhKMVpTd2ljSEpsWm1WeWNtVmtYM1Z6WlhKdVlXMWxJam9pZEhWNlgzTnpaRjlwYm5SbGNuTmxjblpwWTJVaUxDSm5hWFpsYmw5dVlXMWxJam9pSWl3aVptRnRhV3g1WDI1aGJXVWlPaUlpTENKbGJXRnBiQ0k2SW5SMWVsOXpjMlJmYVc1MFpYSnpaWEoyYVdObFFIWnZaR0V1WjI5MkxuSjFJbjAuT290NmtXSWp4b1hQZ0k3ZVBRc2gwN3ZNY0N5SlN0dzVROVVHRWJZVGRiMWNOQWtHV1lZVjRiWUkybDUtdnowNjU1R3k1dXlOcW45Y0VQblBRdUc5RzlseVpkalJIXzQzSHRZYzV4QXZSUHMtLWlOT1llRXdWT3ZqemFQenZ3R3l1aEtPb18xQXJxTkRHM3pVY2o0eWJhS2o1bnlydWg2RTN1cE84LXEtLVNMT2JnU0pUVlZMUnQtX0lmd3FhME9aWVhGU3dHb0J1SDRLRml1X2t2TUg4Z2ZXV3VXX3hfcF9KdnRyeVd6T1czb0NVTmQ0blpiNk9ZeDVRU0NhNFNTdWFJY0dHRm5oeUxZVjJVRS1TT2swUzVLTktZMmdyVmFYV2NLWmFLRlZVd0JjVmctdEJwWEVrakhpRXBvcG5hZHhsWXlpdzRSSjVGcXUxdTVuamVmTnZ3
  SSD_ROLE_MANAGER_KC_SECRET: X19zZWNyZXRfZGF0YV9f
  SSD_ROLE_MANAGER_KC_USER: X19zZWNyZXRfZGF0YV9f
